### ISSUE TITLE
homing rockets

### ISSUE THREAD

**Issue by vykpoli** [Remod-org/NextGenPVE#2]
Players have discovered that if you put a mini near the base you can raid it by launching these rockets at the mini

**Comment by RFC1920** [comment]
I am checking.  Since I usually work alone, I first had to make a plugin to stick a player into a copter so that it can be targeted.  Otherwise, just a parked mini doesn't seem to be targetable.

**Comment by RFC1920** [comment]
Unable to duplicate.  The attacking missile still shows as BasePlayer attacking BuildingBlock.
