### ISSUE TITLE
switched to carbon, plugin will not load

### ISSUE THREAD

**Issue by AerynSun61** [Remod-org/NextGenPVE#5]
hello, 

i'm getting an error:
![image](https://github.com/Remod-org/NextGenPVE/assets/168783664/e1468696-ae3f-4842-9967-18e6fc20f312)

offending line 30 in the cs file: using System.Data.SQLite;

not quite sure how to fix this?

thank you!

**Comment by RFC1920** [comment]
Switch back to Oxide?  Or, perhaps Carbon can shed some light on this.

**Comment by RFC1920** [comment]
That said, I may have an update that will work using Mono.Data.Sqlite instead.. Stay tuned.

**Comment by RFC1920** [comment]
Please try 1.6.7 and let me know.
